services:
  - type: web
    name: agentic-scraper-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: N8N_WEBHOOK_URL
        value: https://fratztechno.app.n8n.cloud/webhook-test/e2852301-dd81-4e81-a108-1b8ed3ee00a9
    plan: free
